# Generated by Django 4.2.20 on 2025-03-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('postId', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
